### ISSUE TITLE
Powerboost taxing.

### ISSUE THREAD

**Issue by Siigillum** [StarQuestMinecraft/StarQuestPublic#732]
I have not beeen taxed for the purchased powerboost for a few days now.

Seems like taxes are not working and on top of that those are laughable anyway - 10c / chunk?

**Comment by awangatboo** [comment]
I can say this.  It is strange as to when it takes money out.  I have seen it take money out but there is not reason I can figure out as to when it will do this.

**Comment by Millibyte1** [comment]
Could it have something to do with the midnight server reboot? It occurs sometime within a 45 minute window of 12:00pm EST, but never at exactly the same time. If the timer for the once-a-day faction tax is for some reason reset upon server restart, the inconsistency of the server reboot time would explain the sporadicity of the taxing.

**Comment by awangatboo** [comment]
I have been told the /powerboost issue is fixed please confirm.

**Comment by Siigillum** [comment]
Taxing possibly works now. Testing further.

Issue with powerboost purchasing still exists. Each purchase replaces the previous one instead of adding up.

**Comment by brickworm2012** [comment]
In or outside of faction claims? What planet?

**Comment by awangatboo** [comment]
Tax is working at this point
